package com.roy.autoBean;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_name
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.tel
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nick_name
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.head_img
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private String headImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.rate
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private Float rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.status
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_date
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_date
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.pwd
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.signature
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.creat_id
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private Long creatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.delete_state
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    private Integer deleteState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_name
     *
     * @return the value of member.member_name
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_name
     *
     * @param memberName the value for member.member_name
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.tel
     *
     * @return the value of member.tel
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.tel
     *
     * @param tel the value for member.tel
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nick_name
     *
     * @return the value of member.nick_name
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nick_name
     *
     * @param nickName the value for member.nick_name
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.head_img
     *
     * @return the value of member.head_img
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.head_img
     *
     * @param headImg the value for member.head_img
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.rate
     *
     * @return the value of member.rate
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public Float getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.rate
     *
     * @param rate the value for member.rate
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setRate(Float rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.status
     *
     * @return the value of member.status
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.status
     *
     * @param status the value for member.status
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_date
     *
     * @return the value of member.create_date
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_date
     *
     * @param createDate the value for member.create_date
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_date
     *
     * @return the value of member.update_date
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_date
     *
     * @param updateDate the value for member.update_date
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pwd
     *
     * @return the value of member.pwd
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pwd
     *
     * @param pwd the value for member.pwd
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.signature
     *
     * @return the value of member.signature
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.signature
     *
     * @param signature the value for member.signature
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.creat_id
     *
     * @return the value of member.creat_id
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public Long getCreatId() {
        return creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.creat_id
     *
     * @param creatId the value for member.creat_id
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setCreatId(Long creatId) {
        this.creatId = creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.delete_state
     *
     * @return the value of member.delete_state
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public Integer getDeleteState() {
        return deleteState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.delete_state
     *
     * @param deleteState the value for member.delete_state
     *
     * @mbg.generated Fri Nov 27 21:32:01 CST 2020
     */
    public void setDeleteState(Integer deleteState) {
        this.deleteState = deleteState;
    }
}